/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2019-07-10 12:55:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("   <head>\n");
      out.write("      <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("      <title>永和大王</title>\n");
      out.write(" \n");
      out.write("      <!--在网页中引入外部的css文件\n");
      out.write("         href指定文件位置\n");
      out.write("       -->\n");
      out.write("      <link rel=\"stylesheet\" href=\"order.css\"/>  \n");
      out.write("   </head>\n");
      out.write("   <body>\n");
      out.write("      <div>顾客联</div>\n");
      out.write("      <div class=\"me\">请您留意取餐账单号</div>\n");
      out.write("      <div class=\"middle\">自取顾客联</div>\n");
      out.write("      <div>永和大王（北三环西路店）</div>\n");
      out.write("      <div>010-62112313</div>\n");
      out.write("      <div class=\"middle\">--结账单--</div>\n");
      out.write("      <div class=\"me\">账单号：P000010</div>\n");
      out.write("      <div>账单类型：堂食</div>\n");
      out.write("      <div>人数：1</div>\n");
      out.write("      <div>收银员：张静</div>\n");
      out.write("      <div>开单时间：2018-04-17 07:24:29</div>\n");
      out.write("      <div>结账时间：2018-04-17 07:24:38</div>\n");
      out.write("     \n");
      out.write("      <hr style=\"border:1px dashed;\"/>\n");
      out.write("     \n");
      out.write("      <div><!-- 插入表格1 -->\n");
      out.write("         <table><!-- 向网页中插入一个表格 -->\n");
      out.write("            <tr><!-- 表示表格中的行元素 -->\n");
      out.write("                <td>数量</td><!-- 表示行中的列元素 -->\n");
      out.write("                <td>品项</td>\n");
      out.write("                <td>金额</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>1</td>\n");
      out.write("                <td>玉米肉松蛋饼2P</td>\n");
      out.write("                <td>8.00</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>&nbsp;</td><!-- 表示行中的列元素 -->\n");
      out.write("                <td>1X --玉米肉松蛋饼</td>\n");
      out.write("                <td>&nbsp;</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("                <td>&nbsp;</td><!-- 表示行中的列元素 -->\n");
      out.write("                <td>1X --现磨豆浆（热/甜）</td>\n");
      out.write("                <td>&nbsp;</td>\n");
      out.write("            </tr>\n");
      out.write("           \n");
      out.write("         </table>\n");
      out.write("      </div>\n");
      out.write("     \n");
      out.write("      <hr style=\"border:1px dashed;\"/>\n");
      out.write("     \n");
      out.write("      <div>\n");
      out.write("         <table>\n");
      out.write("             <tr>\n");
      out.write("               <td width=\"110px;\">合计</td>\n");
      out.write("               <td>8.00</td>\n");
      out.write("             </tr>\n");
      out.write("             <tr>\n");
      out.write("               <td>微支付</td>\n");
      out.write("               <td>8.00</td>\n");
      out.write("             </tr>\n");
      out.write("         </table>\n");
      out.write("      </div>\n");
      out.write("     \n");
      out.write("      <hr style=\"border:1px dashed;\"/>\n");
      out.write("     \n");
      out.write("      <div>打印时间：2018-04-17 07:24:38</div>\n");
      out.write("      <hr style=\"border:1px dashed;\"/>\n");
      out.write("  \n");
      out.write("      <div class=\"note\">\n");
      out.write("      根据相关税法规定，\n");
      out.write("      电子发票的开票日期同网上申请电子发票的日期，\n");
      out.write("      如您需要当日的电子发票请务必在消费\n");
      out.write("      当日通过扫描下方二维码，\n");
      out.write("      根据指引步骤开具您的增值税电子普通发票。\n");
      out.write("      此二维码30天有效，扫描时请保持小票平整。\n");
      out.write("      </div>\n");
      out.write(" \n");
      out.write("      <!-- 向网页中插入一张图片 -->\n");
      out.write("      <div class=\"qrimg\">\n");
      out.write("         <img src=\"qr.png\"/>\n");
      out.write("      </div>\n");
      out.write("     \n");
      out.write("      <!-- 最后两行 -->\n");
      out.write("      <div>官网：www.yonghe.com.cn</div>\n");
      out.write("      <div>加盟热线：86-21-60769397 或 86-21-60769002</div>\n");
      out.write("时\n");
      out.write("   </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
